-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."SoftCartDimDate"
(
    dateid integer NOT NULL,
    year integer,
    month integer,
    monthname character varying(20),
    day integer,
    weekday integer,
    weekdayname character varying(20),
    PRIMARY KEY (dateid)
);

CREATE TABLE IF NOT EXISTS public."SoftCartFactSales"
(
    orderid integer NOT NULL,
    itemid integer,
    categoryid integer,
    price real,
    countryid integer,
    dateid integer NOT NULL,
    PRIMARY KEY (orderid)
);

CREATE TABLE IF NOT EXISTS public."SoftCartDimItem"
(
    itemid integer NOT NULL,
    itemname integer,
    PRIMARY KEY (itemid)
);

CREATE TABLE IF NOT EXISTS public."SoftCartDimCountry"
(
    countryid integer NOT NULL,
    countryname character varying(30),
    PRIMARY KEY (countryid)
);

CREATE TABLE IF NOT EXISTS public."SoftCartDimCategory"
(
    categoryid integer NOT NULL,
    categoryname character varying(30),
    PRIMARY KEY (categoryid)
);

ALTER TABLE IF EXISTS public."SoftCartFactSales"
    ADD FOREIGN KEY (itemid)
    REFERENCES public."SoftCartDimItem" (itemid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SoftCartFactSales"
    ADD FOREIGN KEY (categoryid)
    REFERENCES public."SoftCartDimCategory" (categoryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SoftCartFactSales"
    ADD FOREIGN KEY (countryid)
    REFERENCES public."SoftCartDimCountry" (countryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SoftCartFactSales"
    ADD FOREIGN KEY (dateid)
    REFERENCES public."SoftCartDimDate" (dateid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;